# CCVE Prometheus Exporter for Flux Operator
# Exports CCVE findings as Prometheus metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccve-exporter
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccve-exporter
rules:
  # Read Flux resources
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Read Flux Operator resources
  - apiGroups: ["fluxcd.controlplane.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Read workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ccve-exporter
subjects:
  - kind: ServiceAccount
    name: ccve-exporter
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: ccve-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccve-exporter
  namespace: flux-system
  labels:
    app.kubernetes.io/name: ccve-exporter
    app.kubernetes.io/part-of: confighub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ccve-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ccve-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ccve-exporter
      containers:
        - name: exporter
          image: ghcr.io/confighub/ccve-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - --metrics-port=9090
            - --scan-interval=60s
            - --ccve-database=/etc/ccve/index.json
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
            - containerPort: 8080
              name: api
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: ccve-database
              mountPath: /etc/ccve
              readOnly: true
      volumes:
        - name: ccve-database
          configMap:
            name: ccve-database
---
apiVersion: v1
kind: Service
metadata:
  name: ccve-exporter
  namespace: flux-system
  labels:
    app.kubernetes.io/name: ccve-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ccve-exporter
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
    - name: api
      port: 8080
      targetPort: api
---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ccve-exporter
  namespace: flux-system
  labels:
    app.kubernetes.io/name: ccve-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ccve-exporter
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
---
# ConfigMap with CCVE database (generated from confighub-scan/risks/index.json)
apiVersion: v1
kind: ConfigMap
metadata:
  name: ccve-database
  namespace: flux-system
data:
  index.json: |
    {
      "version": "0.1.0",
      "count": 25,
      "ccves": [
        {"id": "CCVE-2025-0001", "category": "SOURCE", "severity": "critical"},
        {"id": "CCVE-2025-0004", "category": "RENDER", "severity": "critical"},
        {"id": "CCVE-2025-0008", "category": "DEPEND", "severity": "warning"},
        {"id": "CCVE-2025-0009", "category": "STATE", "severity": "info"}
      ]
    }
---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ccve-alerts
  namespace: flux-system
spec:
  groups:
    - name: ccve
      rules:
        - alert: CCVECriticalFinding
          expr: ccve_findings_total{severity="critical"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Critical CCVE detected"
            description: "{{ $value }} critical Config CVE(s) detected in cluster"
        - alert: CCVEWarningFindings
          expr: ccve_findings_total{severity="warning"} > 5
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Multiple warning CCVEs detected"
            description: "{{ $value }} warning Config CVE(s) detected in cluster"
