# Realistic Orphan Resources for cub-scout Demo
#
# These resources simulate what accumulates in real clusters:
# - Legacy systems that predate GitOps adoption
# - Temporary debugging resources someone forgot to delete
# - Manual hotfixes applied during incidents
# - ConfigMaps and Secrets from kubectl operations
#
# NONE of these have GitOps labels, so cub-scout will detect them as "Native" (orphans).
#
# Usage:
#   kubectl apply -f realistic-orphans.yaml
#   cub-scout map orphans
#
# Cleanup:
#   kubectl delete -f realistic-orphans.yaml

---
# Namespace for legacy applications that predate GitOps
apiVersion: v1
kind: Namespace
metadata:
  name: legacy-apps
  labels:
    purpose: "predates-gitops"

---
# Namespace for temporary testing
apiVersion: v1
kind: Namespace
metadata:
  name: temp-testing
  labels:
    purpose: "debugging"

---
# =============================================================================
# LEGACY MONITORING - predates GitOps adoption
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-prometheus
  namespace: legacy-apps
  annotations:
    deployed-by: "kubectl by ops team, 2023-06-15"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-prometheus
  template:
    metadata:
      labels:
        app: legacy-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.45.0
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: legacy-prometheus
  namespace: legacy-apps
spec:
  selector:
    app: legacy-prometheus
  ports:
  - port: 9090
    targetPort: 9090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: legacy-prometheus-config
  namespace: legacy-apps
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: 'legacy-apps'
        static_configs:
          - targets: ['localhost:9090']

---
# =============================================================================
# TEMPORARY DEBUGGING - someone forgot to delete
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-nginx
  namespace: temp-testing
  annotations:
    created-by: "alice@company.com during incident INC-2847"
    delete-after: "2024-01-15"  # oops, that was a year ago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-nginx
  template:
    metadata:
      labels:
        app: debug-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: debug-nginx
  namespace: temp-testing
spec:
  selector:
    app: debug-nginx
  ports:
  - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-busybox
  namespace: temp-testing
  annotations:
    purpose: "network debugging during outage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-busybox
  template:
    metadata:
      labels:
        app: debug-busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.36
        command: ["sleep", "infinity"]

---
# =============================================================================
# MANUAL HOTFIXES - applied during incidents
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotfix-worker
  namespace: default
  annotations:
    incident: "INC-3921 - applied at 2am to handle queue backlog"
    revert-by: "never documented"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotfix-worker
  template:
    metadata:
      labels:
        app: hotfix-worker
    spec:
      containers:
      - name: worker
        image: busybox:1.36
        command: ["sh", "-c", "while true; do echo processing; sleep 60; done"]

---
apiVersion: v1
kind: Service
metadata:
  name: hotfix-worker
  namespace: default
spec:
  selector:
    app: hotfix-worker
  ports:
  - port: 8080

---
# =============================================================================
# CONFIGMAPS - manual overrides that accumulate
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: old-feature-flags
  namespace: default
  annotations:
    last-updated: "2023-09-20"
data:
  enable_v2_api: "false"
  deprecated_auth_flow: "true"
  experimental_cache: "false"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manual-override
  namespace: default
  annotations:
    incident: "applied during INC-2847"
    applied-by: "bob@company.com"
data:
  override_reason: "applied at 2am during incident - TODO: add to GitOps"
  rate_limit: "10000"
  timeout_ms: "30000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: legacy-app-config
  namespace: legacy-apps
data:
  database_host: "legacy-db.internal"
  cache_enabled: "true"
  log_level: "warn"

---
# =============================================================================
# SECRETS - manually created during operations
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: manual-api-key
  namespace: default
  annotations:
    purpose: "manually added during debugging session"
type: Opaque
stringData:
  api_key: "manual-key-replace-with-gitops"

---
apiVersion: v1
kind: Secret
metadata:
  name: legacy-db-credentials
  namespace: legacy-apps
type: Opaque
stringData:
  username: "legacy_app"
  password: "should-be-in-vault"

---
# =============================================================================
# CRONJOBS - scheduled tasks added manually
# =============================================================================

apiVersion: batch/v1
kind: CronJob
metadata:
  name: manual-cleanup
  namespace: default
  annotations:
    purpose: "cleans up old data - should be in GitOps"
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: busybox:1.36
            command: ["echo", "cleanup job running"]
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: legacy-backup
  namespace: legacy-apps
  annotations:
    created: "2022-03-15"
    owner: "unknown - original author left company"
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox:1.36
            command: ["echo", "backup running"]
          restartPolicy: OnFailure

---
# =============================================================================
# MISC ORPHANS - various leftover resources
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: legacy-service-account
  namespace: legacy-apps

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-storage
  namespace: temp-testing
  annotations:
    purpose: "temporary storage for debugging - delete when done"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: legacy-allow-all
  namespace: legacy-apps
  annotations:
    reason: "added to fix connectivity issue - too permissive"
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
