apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delivery-tree-elsewhere
  namespace: delivery-tree-elsewhere-apps
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.revision | quote }}
    path: examples/delivery-tree/argocd/workloads/jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: delivery-tree-elsewhere
  # In a namespace this Argo CD is not configured to read Applications from.
  syncPolicy:
    automated: {}
