# PostgreSQL via Flux HelmRelease
# This is an example of deploying a database through GitOps
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "13.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Base values - overridden by environment-specific patches
    auth:
      database: platform
      existingSecret: postgresql-credentials
    primary:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
